"""External service integrations."""

from .smtp_email import (
    SMTPConfig,
    SMTPEmailService,
    EmailMessage,
    EmailAttachment,
    SendResult,
    get_smtp_service,
    configure_smtp_service,
)
from .scheduling import (
    SchedulingProvider,
    MeetingType,
    InjectionStyle,
    AvailabilitySlot,
    SchedulingLink,
    SchedulingConfig,
    SchedulingService,
    SchedulingConfigStorage,
    MessageInjector,
    CalendlyClient,
    CalComClient,
    validate_scheduling_url,
    create_scheduling_link,
    detect_provider,
    get_config_storage,
)
from .greenhouse_client import (
    GreenhouseClient,
    GreenhouseJob,
    GreenhouseJobListItem,
    GreenhouseBoardInfo,
    GreenhouseLocation,
    GreenhouseDepartment,
    GreenhouseOffice,
    GreenhouseMetadata,
    GreenhouseClientError,
    GreenhouseNotFoundError,
    GreenhouseRateLimitError,
    GreenhouseAPIError,
    fetch_greenhouse_jobs,
    fetch_greenhouse_job_details,
    fetch_jobs_from_multiple_boards,
)
from .lever_client import (
    LeverClient,
    LeverPosting,
    LeverPostingListItem,
    LeverCategories,
    LeverContentBlock,
    LeverClientError,
    LeverNotFoundError,
    LeverRateLimitError,
    LeverAPIError,
    ResponseMode,
    fetch_lever_postings,
    fetch_lever_posting_details,
    fetch_postings_from_multiple_companies,
)

__all__ = [
    # SMTP Email
    "SMTPConfig",
    "SMTPEmailService",
    "EmailMessage",
    "EmailAttachment",
    "SendResult",
    "get_smtp_service",
    "configure_smtp_service",
    # Scheduling Enums
    "SchedulingProvider",
    "MeetingType",
    "InjectionStyle",
    # Scheduling Models
    "AvailabilitySlot",
    "SchedulingLink",
    "SchedulingConfig",
    # Scheduling Services
    "SchedulingService",
    "SchedulingConfigStorage",
    "MessageInjector",
    # Scheduling API Clients
    "CalendlyClient",
    "CalComClient",
    # Scheduling Functions
    "validate_scheduling_url",
    "create_scheduling_link",
    "detect_provider",
    "get_config_storage",
    # Greenhouse Job Board API
    "GreenhouseClient",
    "GreenhouseJob",
    "GreenhouseJobListItem",
    "GreenhouseBoardInfo",
    "GreenhouseLocation",
    "GreenhouseDepartment",
    "GreenhouseOffice",
    "GreenhouseMetadata",
    "GreenhouseClientError",
    "GreenhouseNotFoundError",
    "GreenhouseRateLimitError",
    "GreenhouseAPIError",
    "fetch_greenhouse_jobs",
    "fetch_greenhouse_job_details",
    "fetch_jobs_from_multiple_boards",
    # Lever Postings API
    "LeverClient",
    "LeverPosting",
    "LeverPostingListItem",
    "LeverCategories",
    "LeverContentBlock",
    "LeverClientError",
    "LeverNotFoundError",
    "LeverRateLimitError",
    "LeverAPIError",
    "ResponseMode",
    "fetch_lever_postings",
    "fetch_lever_posting_details",
    "fetch_postings_from_multiple_companies",
]
